from provaListaDuplamente import  Lista
from provaArvore import Arvore
lista = Lista()
lista.add_inicio(25)
lista.add_inicio(50)
lista.add_fim(10)
lista.add_index(3, 20)
lista.add_index(0, 30)
lista.add_index(1, 15)
lista.add_index(3, 39)
print(lista)
lista.remover(2)
print(lista)
arvore = Arvore()
arvore.add(25)
arvore.add(50)
arvore.add(10)
arvore.add(20)
arvore.add(30)
arvore.add(15)
arvore.add(39)
arvore.imprimir()
print('------------------------')
print('nível:',arvore.altura(arvore.raiz))
print('------------------------')
print('contagem de todos os nós:',arvore.contarNos(arvore.raiz))
print('------------------------')
a=arvore.Listar()
print(a)

