from arvore1 import Arvore

arvore = Arvore()
arvore.add(25)
arvore.add(50)
arvore.add(40)
arvore.add(6)
arvore.add(10)
arvore.add(15)
arvore.add(39)
arvore.imprimir()
print("\n")
print(arvore.min(arvore.raiz))
print(arvore.max(arvore.raiz))
print('------------------------')
print(arvore.sucessor(arvore.raiz))
print('------------------------')
print(arvore.predecessor(arvore.raiz))
# print('------------------------')
# pai, pos, perc = arvore.buscar_(15)
# print('------------------------')
# print("Pai",pai)
# print("Perc",perc)
# print("Pos", pos)
print('------------------------')
arvore.remover(10)
print('------------------------')
arvore.imprimir()
print('------------------------')
print('nível:',arvore.altura(arvore.raiz))
print('------------------------')
print('contagem de todos os nós:',arvore.contarNos(arvore.raiz))
print(arvore.total_de_elementos_nó(15))
print('folhas:',arvore.folhas(arvore.raiz))
print(arvore.ListaremOrdem(arvore.raiz))
print('nível:',arvore.nível_de_cada_elemento(15,0))

#print(arvore.addNoBalanceado(arvore.raiz,10))

